version: '3.8'

services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_sql_scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build: ./backend
    image: tsmith4014/backend
    ports:
      - "${PORT_BACKEND}:3001"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      PORT: ${PORT_BACKEND}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: tsmith4014/frontend
    ports:
      - "${PORT_FRONTEND}:3000"
    environment:
      REST_API_URL: http://backend:${PORT_BACKEND}/data
      PORT: ${PORT_FRONTEND}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: